Information:
  Title: Layeredy announcements
  Description: Important announcements and updates from Layeredy.
  Link: layeredy.com
  Theme: Layeredy

Connections:
  GitHub: 
  YouTube:
  Twitter: 
  Mastodon: 
