Information:
  Title: Layeredy announcements
  Description: News and announcements site for Layeredy
  Link: layeredy.com
  Theme: Layeredy

Connections:
  GitHub: layeredy
  YouTube:
  Twitter: 
  Mastodon: 
